### ISSUE TITLE
cyto_gate_draw: show line connecting last placed point to mouse cursor

### ISSUE THREAD

**Issue by stefankolling** [DillonHammill/CytoExploreR#26]
Hi Dillon,

I've just stumbled about your project a few days ago and am working my way through the vignettes right now. First of all, thanks a lot for coming up with CytoExploreR - it's an excellent starting point for me to move from manual gating in FlowJo to a hybrid manual/automated gating with the openCyto framework and eventually migrate to fully automated gating (hopefully)!

A future feature I would find useful when manually drawing polygon gates with cyto_gate_draw would be to already see a line connecting the last placed gate point to the moving mouse cursor. This way it would be a bit easier to place the gate points and be sure to include all the cells you wanted. Similarly, for the other gate types, it would be great to already see the gate's outline before placing the last gate point.

Thanks again for the great work.

Cheers,
Stefan

PS: If this isn't the right place to post such ideas, just let me know.

**Comment by DillonHammill** [comment]
Thanks for using CytoExploreR @stefankolling!

Unfortunately, due to the fact that the plots are not live in R, this feature is not possible at the moment. With a little practice you will be a pro in no time!

The best way to do it is to draw a gate with `cyto_gate_draw` and then change `draw` in that call to `edit`. This will display the old gate as a guide and let you make fine adjustments (re-draw the gate).

Dillon

**Comment by stefankolling** [comment]
Thanks, I appreciate the answer! Resorting to cyto_gate_edit is exactly what I did, but I didn't know R well enough to understand that there was a reason for this feature not being present.

Keep up the great work!
