### ISSUE TITLE
error in load_cytoset_from_fcs when emptyValue = FALSE

### ISSUE THREAD

**Issue by Biomiha** [DillonHammill/CytoExploreR#37]
It seems that load_cytoset_from_fcs doesn't actually accept the emptyValue argument. When I read in a set of fcs files using `read.flowSet(fcs_files, emptyValue = FALSE)` this works but when I try the same with `load_cytoset_from_fcs(fcs_files, emptyValue = FALSE)`, I get the following error:

Error_ in fcs_to_cytoset(sapply(files, normalizePath), list(which.lines = which.lines,  : 
  Empty keyword name detected!If it is due to the double delimiters in keyword value, please set emptyValue to FALSE and try again!

**Comment by Biomiha** [comment]
Just realised `load_cytoset_from_fcs` is actually part of flowWorkspace. Apologies.

**Comment by DillonHammill** [comment]
The CytoExploreR wrapper for this is `cyto_load()` which calls these functions internally. `cyto_load()` is called inside `cyto_setup()` to read in the files. All exported CytoexploreR functions are prefixed with `cyto_`.

**Comment by Biomiha** [comment]
I get the same issue with `cyto_load`, e.g.:

`cyto_load(path = fcs_files, select = list.files(fcs_files, pattern = "fcs"), emptyValue = FALSE)`

Error in fcs_to_cytoset(sapply(files, normalizePath), list(which.lines = which.lines,  : 
  Empty keyword name detected!If it is due to the double delimiters in keyword value, please set emptyValue to FALSE and try again!

**Comment by DillonHammill** [comment]
That is to be expected, the same function is being called.

Have you tried looping through the files individually and calling `load_cytoframe_from_fcs()`. Perhaps the argument is not being passed on to this function from `load_cytoset_from_fcs()`?

```{r}
files <- list.files("fcs_files", full.names = TRUE)
cf_list <- lapply(files, function(file){load_cytoframe_from_fcs(file, emptyValue = FALSE))
cs <- cytoset(cf_list)
```

**Comment by Biomiha** [comment]
I still get an error:


    files <- list.files("fcs_files", pattern = "fcs", full.names = TRUE)
    cf_list <- lapply(files, function(file){load_cytoframe_from_fcs(file, emptyValue = FALSE)})
    cs <- cytoset(cf_list)


Error in parseFCS(normalizePath(filename), list(which.lines = which.lines,  : 
  Empty keyword name detected!If it is due to the double delimiters in keyword value, please set emptyValue to FALSE and try again!

**Comment by DillonHammill** [comment]
If `read.flowSet()` works just use this and then conver the flowSet to a cytoset if you need to:

```{r}
files <- list.files("fcs_files", pattern = "fcs", full.names = TRUE)
fs <- read.flowSet(files, emptyValue = FALSE)
cs <- flowSet_to_cytoset(fs)
```

I would still file an issue on flowWorkspace as well, so that this can be fixed.

**Comment by Biomiha** [comment]
Yes. This works as well.

    files <- list.files("fcs_files", pattern = "fcs", full.names = TRUE)
    cf_list <- lapply(files, function(file){read.FCS(file, emptyValue = FALSE)})
    cs <- cytoset(cf_list)

**Comment by DillonHammill** [comment]
For anyone else experiencing the same problem this has now been fixed. If you need this feature you will need the latest versions of `cytolib` and `flowWorkspace`.

**Comment by BenJCQuah** [comment]
Dear Dillon Hammill,

Thank you for your awesome better-than-flowjo flow Cytometry analysis package.  I recently came across the latest version of this package and have been implementing the PaCMAP cyto_map() function and have come across a similar error to that posted above while doing so.  The code I was using is as follows:
________________________
gs_pacmap <- cyto_map(
  gs,
  select=c(1:30),
  parent = "singlets2",
  channels = c(
    "FSC-A", 
    "SSC-A",
    "FSC-H",
    "FSC-W",
    "SSC-H",
    "SSC-W",
    cyto_markers(
      gs
    )
  ),
  type = "PaCMAP",
  events = 1,
  label = "PaCMAP"
)
________________________
and the error I had was as follows after running this.
________________________
Error in fcs_to_cytoset(sapply(files, normalizePath), list(which.lines = which.lines,  : 
  Empty keyword name detected!If it is due to the double delimiters in keyword value, please set emptyValue to FALSE and try again!
________________________

Is there a know fix for this?

Thanks for your time.

BQ
