### ISSUE TITLE
FEATURE DEMO:How to control overlay behaviour

### ISSUE THREAD

**Issue by Biomiha** [DillonHammill/CytoExploreR#38]
Hi Dillon,

I've been struggling to get a handle on how the overlay feature decides how many events to plot with regard to the main population. We've got a GatingSet with 4 samples of ~2.5M cells each. We've also got index files (roughly 5000 cells in total) from cells that were sorted from these 4 samples. What I'd like is to be able to do is to downsample only the tubes samples when gating but plot the total ~5000 sorted cells overlaid on the plot whilst drawing the gate. If I set the display value to 1, it takes an obscene amount of time to plot, but if I downsample, I don't see the overlaid points anymore. Passing a vector of values to display doesn't seem to work as it just takes the first value. Is there a way of being able to control this behaviour?

Many thanks in advance.

**Comment by DillonHammill** [comment]
@Biomiha, this is a known issue. The sampling within `cyto_plot()` is quite complex. At the moment `cyto_gate_draw()` has its own sampling logic, which needs to be updated. I will work to make these the same and report the outcome here. I will however, not allow sampling per layer - the same level of sampling must be applied to all layers within the same plot.

**Comment by Biomiha** [comment]
@DillonHammill I've looked at the source code and I think I get what's going on. The overlay is appended to the cytoset and then the dowsampling is performed on the total number of cells, which would explain some of the "randomness" of the number of overlaid points being plotted. For some reason (or it might be just our dataset) the "root" layer seems to be exempt from this behaviour. 
I am tempted to think that this is a scientifically legitimate scenario where plotting all of the sorted cells on top of the parent layer should be allowed but I understand your reservations.

**Comment by DillonHammill** [comment]
@Biomiha, sorry it took so long to address this issue. I have been working on a lot of things which will be released over the coming days so I would like to get this sorted out as well. I have put some notes below in case I need to re-visit this issue sometime in the future:

**Sampling in cyto_plot()**
`cyto_plot()` uses a custom version of `cyto_sample()` which performs additional scaling to maintain population proportions. Basically, if we plot the T Cells for Activation_1.fcs and overlay the CD4 T Cells for Activation_1.fcs and use the default sampling of 25 000 events, the bottom layer gets down sampled to 25 000 events and subsequent layers get down sampled their count / bottom layer count * 25 000. This ensures that the original proportions are retained when the data is down sampled - i.e. if we simply down sampled both layers to 25 000 events there would be an over representation of the CD4 T Cells. The sampling method within `cyto_plot()` also accounts for cases where the samples contain less than the desired number of events (i.e. if the bottom layer only contains 10 000 events then subsequent layers are sampled as count/bottom layer count * 10 000).

Obviously, this proportional down sampling is not always desirable. For example, if we plot the T Cells from Activation_1.fcs and overlay the T Cells from Activation_2.fcs, we would just want to apply the same amount of down sampling to each layer. To overcome this, the sampling method in `cyto_plot()` only applies proportional down sampling when the layers come from the same original sample. Since these layers come from separate samples (Activation_1.fcs and Activation_2.fcs) they will be down sampled to the same extent (i.e. 25 000 events per layer).

To further complicate matters, `cyto_plot()` has support for complex overlays through `group_by()`. For example, we could merge samples by `Treatment` and overlay them on top of one another. This poses additional challenges, as each `Treatment` group could contain a different number of samples and therefore each group can contain a vastly different number of events (this difference should be reflected in the resulting down sampled plot). Correcting for this is challenging and suspect this is why it is supported in other software platforms. Nevertheless, the sampling method in `cyto_plot()` tries its best to appropriately down sample each layer by considering the number of merged samples per group. For example, if the bottom layer consists of 3 merged samples (50 000 events each) and the next layer contains 5 merged samples (50 000 events each). If the bottom layer is down sampled to 25 000 events, the next layer should be down sampled to 5/3 * 25000 to maintain the original sample proportions. In this example, each of the samples has the same number of events but this is not always the case, `cyto_plot()` tries to account for this using the average number of events per sample. 

Hopefully you can now see that a lot of thought has gone into the sampling within `cyto_plot()` and it is not just as straightforward as applying the same level of sampling to everything. `cyto_plot()` will do its best to provide plots that best represent the data.

To ensure that your data is always properly down sampled I would recommend that you analyze the same number of events for each of your samples. For example, once you have loaded your samples in with `cyto_setup()` you could follow this up with a call to `cyto_sample()` to get the same number of events in each sample before you start your analysis. I have just added a GatingSet method for `cyto_sample()` to allow you to do this. In fact now that I think about this, there should be a sample argument in `cyto_setup()` to allow you to do this when the samples are loaded. I just added this feature too, if you set `sample = TRUE` it can down sample each sample to the minimum number of events in a single file or you can supply the number of events manually:

```{r}
# Load samples & sample to minimum count
gs <- cyto_setup("Samples",
                 clean = TRUE,
                 sample = TRUE,
                 gatingTemplate = "gatingTemplate.csv")

# Load samples & sample 50 000 events
gs <- cyto_setup("Samples",
                 clean = TRUE,
                 sample = 50000,
                 gatingTemplate = "gatingTemplate.csv")
```

**Sampling in cyto_gate_draw()**
Currently, `cyto_gate_draw()` actually uses its own sampling method. The reason for this is because when gating we often want to overlay just a single sample (e.g. unstained control or FMO) and so we don't want proportional sampling to happen here (there will be too few events plotted - as is currently the case). Looking at the code it looks like I may have changed this when I last updated `cyto_sample()` so that this proportional sampling is still occurring. I will need to think about this a bit more, but I suspect that it is probably OK if I ditch all proportional sampling in `cyto_gate_draw()` and instead allow it to plot the same number of events per layer. I will sleep on this and make the changes tomorrow morning - it will be an easy fix.

**Comment by DillonHammill** [comment]
@Biomiha, I decided to remove the proportional sampling in `cyto_gate_draw()` and `cyto_gate_edit()`. This means that each layer will now be subjected to the same level of sampling. The sampling method in `cyto_plot()` remains unchanged. Please pull down the latest CytoExploreR and let me know how you go (shouldn't need to update RGLab packages - binaries are available on BioC if you need them):
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by DillonHammill** [comment]
CytoExploreR version 2.0.0 deploys a much more sophisticated sampling routine within `cyto_plot()`.

In the new version, your data must first be barcoded using `cyto_barcode(gs, type = "events")` - the new `cyto_setup()` will take care of that for you.

Here is a summary of the changes:
- `display` has been renamed to `events` for consistency with other functions and it is much easier to type correctly.
- setting `events = 0` will get `cyto_plot()` to compute the minimum number of events across all samples and downsample to that number of events.
- setting `events < 0` indicates the proportion of events to retain.
- setting `events > 0` indicates the number of events to retain
- we now use `cyto_sample_n()` to pre-compute the (proportional) sample size for each cytoframe, and then merge the sampled cytoframes (this offers a major speed boost compared to v1.1.0)
- event IDs are now matched between layers to ensure that EXACTLY the same events are displayed on the plot when adding overlays (pretty cool!).
- thanks to improvements in plotting speed, the `events = 50 000` by default (twice the old default).
