### ISSUE TITLE
Multiplex Bead separation

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#51]
**Briefly describe what you hope to achieve:**
- I am trying to work my way through a multiplex experiment that I have previously looked at in FCS Express.  There are 2 bead populations (a and B) that are separated on size.  Each bead population has 6 or 7 Abs that capture cytokines, and are separated by gating in one channel (FL4).  The amount of capture is then read in a second channel (FL3).  FCS Express version:

![FCSExpressGates](https://user-images.githubusercontent.com/3155051/83052750-5e980580-a015-11ea-9f07-85c50cc469ae.png)

cyto_gate_draw() has let me gate the A and B beads sets in a fairly straight forward fashion.  I'm having trouble with the gates for individual chemokines  within a set.  Perhaps I am doing something wrong with cyto_transform() or my spill correction, but I'm not getting good separation of the ID channel.  I'm not quite sure how to use axis_limits right.  I don't get much different behavior from "auto", "data", and "machine", nor do I know what to expect from auto or data.  I've played a little with just using xlim, but my axes scale is difficult to understand.  Can't see how to request logicle or know how to separate things.  

It says, "Combined events SetA".   Am I using Select wrong?  Of course, I could be messing up with spill correction or transformation.
 
Any suggestions?  Broader, debugging suggestions are entirely welcome.  I'm not very clear yet how to interrogate the various parts of the puzzle yet.

**Outline the steps taken to attempt to reach this goal (paste code below):**
- Include all data preparation steps where appropriate.
```{r}
cyto_gate_draw(gs.unk,
               parent = "SetA",
               alias = "CXCL8",
               axis = "y",
               channels = c("FL3-AREA", "FL4-AREA"),
               select = "0ng_NoBlock_A1.fcs",
               type = "interval",
               axis_limits = "data")
```

My image in cytoexploreR for drawing the first gate:
![SetGates](https://user-images.githubusercontent.com/3155051/83057010-ee40b280-a01b-11ea-92a1-e8515462b629.png)

![CXCL8_GateDraw](https://user-images.githubusercontent.com/3155051/83057072-09abbd80-a01c-11ea-9d27-e486225c9ac0.png)

**Comment by DillonHammill** [comment]
@rwbaer, the scales look weird because you have transformed the data multiple times. Make sure that you only apply the transformations once or inverse the transformations before apply new ones. CytoExploreR has a number of `cyto_transformer()` functions for this purpose, they allow you to tweak the transformation parameters before applying them to your data. For consistency, these functions are wrappers for the flowCore/flowWorkspcae transformation functions and accept all their arguments as well (e.g. widthBasis). I have included links to the relevant RGLab functions in the help documentation so that you can see what other arguments are available. Here is an example of how to use the `cyto_transformer()` functions:
```{r}
#Load samples
gs <- cyto_setup("Samples")

# Tweak PE-A biex transformation
PE_trans <- cyto_transformer_biex(gs,
                                  parent = "root",
                                  channels = c("PE-A"),
                                  widthBasis = -100)
```
Since `cyto_transformer_biex()` does not actually apply the transformation to the data, we can iterate through widthBasis (i.e. edit and re-run) until we are happy with the transformation. Then all we need to do is apply our custom transformation to the GatingSet with `cyto_transform()`. It is important to note that you can also use different transformations for each channel using this method, you just need to combine the transformations using `cyto_transformer_combine()` before applying them to the GatingSet. See below for example:
```{r}
# Tweak APC-A biex transformation
APC_trans <- cyto_transformer_logicle(gs,
                                  parent = "root",
                                  channels = c("APC-A"))

# Combine transformatinons
trans <- cyto_transformer_combine(PE_trans, APC_trans)

# Apply transformations to GatingSet
gs <- cyto_transform(gs, trans = trans)
```
I am just documenting this here because I don't think it is documented in detail elsewhere, but note that it is not required to address your original question. In my experience I have had no issue with resolution when analyzing cytokine bead array data using the quick and dirty `cyto_transform()` method. With the following code, you can see that the beads are easily distinguishable in the `Alexa Fluor 647-A` channel (note this includes both Beads A and Beads B).
```{r]
# Load CBA data
gs <- cyto_setup("CBA",
                 markers = FALSE,
                 details = FALSE,
                 gatingTemplate = "CBA-gatingTemplate.csv")

# Transform fluorescent channels
gs <- cyto_transform(gs)
```
![Rplot01](https://user-images.githubusercontent.com/28646736/83086237-88aefd80-a0d1-11ea-8655-ff8452bc395f.png)

These are the steps that I took to gate the data, in case you are interested. Note that the `xlim` and `ylim` arguments are used to zoom in only and do not affect the underlying transformation. There was sufficient resolution for Beads B to gate in just the Alexa Fluor 647-A channel. Theses are rough gates but you get the idea.

```{r}
# BEADS A & BEADS B
cyto_gate_draw(gs,
               parent = "root",
               alias = c("Beads A", "Beads B"),
               channels = c("FSC-A", "SSC-A"))
```
![CBA-1](https://user-images.githubusercontent.com/28646736/83086587-87320500-a0d2-11ea-90ef-bcb9aa4a6637.png)
```{r}
# GATE A1-A6 & B1-B7
cyto_gate_draw(gs,
               parent = "Beads A",
               alias = paste0("A-",1:6),
               channels = c("7-AAD-A", "Alexa Fluor 647-A"),
               type = "r",
               ylim = c(500, 50000))
```
![Rplot02](https://user-images.githubusercontent.com/28646736/83086440-1db1f680-a0d2-11ea-915f-85c66b863d02.png)
```{r}
# GATE B1-B7
cyto_gate_draw(gs,
               parent = "Beads B",
               alias = paste0("B-",1:7),
               channels = c("Alexa Fluor 647-A"))
```
![Rplot04](https://user-images.githubusercontent.com/28646736/83086562-75e8f880-a0d2-11ea-9f9b-0d5d060cb825.png)

FYI soon you will be able to analyze your CBA data from beginning to end using CytoExploreR!

**Comment by rwbaer** [comment]
Very helpful as always and the example workflow is terrific.  Thanks for taking the time to explain things and sharing the workflow.  This will help me inch my way along.  I remain really excited about your project.  Wish I was better at interrogating S4 objects so I din't have to bother you so much.

I'll try to work on understanding how transforms relate to flowsets, gating sets, plots, and workspaces.  I have always thought of them as graph axis transformations, and in standard flow software you can only check one axis transform at once.  Not sure how it is mapped data and plots in cytoExploreR and the RGLab softwares.  Does it work like a stack?  First on, first off?  What object do they live in? flowframe? flowset? gateset?  

Don't feel obligated to answer.  I'm just trying to give you a sense of what us end users need to know.  I understand the burden of learning is on us.
