### ISSUE TITLE
Error in fcs_to_cytoset and HDF5: infinite loop closing library

### ISSUE THREAD

**Issue by Sithara85** [DillonHammill/CytoExploreR#82]
Hi,

I am running the flow cytometry analysis using openCyto and multiple flow cytometry packages from RGLab. We are processing ~10,000 samples. I am getting below error when I reach ~3100 samples. What could be the problem? I am not very familiar with HDF5 library issues. Is it something you can help me with?

Mike has been working with me to resolve some of the issues with CytoML and docker image issues I had when I developed the Rscript. I am using a PBS script to run Rscript and Singularity function to save gatingset and wsp files.

Thank you,
Sithara

**Comment by malcook** [comment]
Having just now resolved this same issue for myself, I thought I'd share my solution here on the chance similarly afflicted might benefit.

In my case, the root cause stemmed from TMPDIR not being large enough to hold all the temporary HDF5 files created by flowWorkspace operations.

It can be challenging to witness this since `R` contrives to cleanup its TMPDIR upon exit.  As part of your diagnostics, you might choose to monitor its usage while your workflow is running.  On linux, you can get see this updated every 2 seconds with:

```
watch du -fl -t tmpfs
```

Assuming this is in fact your problem, the solution-space can be multifold:

 - consider to run fewer jobs in parallel so fewer HDF5 files are needed at once
 - contrive for your workflow to call [cleanup_temp](https://rdrr.io/bioc/flowWorkspace/man/cleanup_temp.html) *at the right time*  (e.g. upon exit from the function in which those objects are created and analyzed), viz: 
 ```
myAnalysis(fcs.path,...) {
    fs<-read.flowSet(fcs.path)
    on.exit(flowWorkspace::cs_cleanup_temp(fs)) # delete files in TMPDIR when this function returns
    ... ##proceed with analysis
}
```
 - `export TMPDIR=/someplace/else/with/more/diskspace` before invoking R
 - allocate more disk to ${TMPDIR}
 - if your HPC cluster admins deploy R containerized as mine do (using singularity), ensure that '/someplace/else/with/more/diskspace' is visible inside the container (else it won't be used by R).  For me, this can be accomplished with `export SINGULARITY_BINDPATH=${TMPDIR}` before calling R. YMMV 🥲
