### ISSUE TITLE
How to order plots or even the gs on a vector instead of file names ?

### ISSUE THREAD

**Issue by SgtVil** [DillonHammill/CytoExploreR#92]
Hello, 
I'm struggling to order my plots alphabetically with a "sample" vector in the cyto_details(). I cannot manage to give the order to the object : cyto_details(gs)= cyto_details(gs)[ order(cyto_details(gs)[,2]),]
It keeps the order from the file names and won't plot in the order I want. I tried with group_by= "sample" which is the name of the vector. 

Thanks a lot.
Rémy

**Comment by DillonHammill** [comment]
@sgtVil, `group_by` will attempt to match the supplied levels to variables within `cyto_details(gs)` - so we need to know which variables and what levels (not indices). In order to do this, you will need to supply this information in a list to `group_by` as below:
```{r}
library(CytoExploreR)
library(CytoExploreRData)

# Prepare data
gs <- GatingSet(Activation)
gs <- cyto_compensate(gs)
gs <- cyto_transform(gs)
gs <- cyto_gatingTemplate_apply(gs, Activation_gatingTemplate)

# Remove unstained control
gs <- gs[-33]

#  Experiment details
cyto_details(gs) 

# Treatment order
order <- c("Stim-D", "Stim-C", "Stim-A", "Stim-B")

# Plot
cyto_plot(gs,
          parent = "CD4 T Cells",
          channels = c("CD44", "CD69"),
          group_by = list(Treatment = order))
```
The approach above will merge samples within the same Treatment group and then order them. If you want to keep the samples separate (without merging) then you will need to do the following:
```{r}
# Extract experiment details
pd <- cyto_details(gs)

# Determine order (indices)
order <- unlist(lapply(order, function(z) {which(pd$Treatment == z)}))

# Plot
cyto_plot(gs[order],
          parent = "CD4 T Cells",
          channels = c("CD44", "CD69"))
```
There is a new `sort_by()` function coming in the next version which will take care of the second scenario for you, there is also a `sort_by` argument coming to `cyto_plot()`.

**Comment by SgtVil** [comment]
Thanks for your quick response, it's quite impressive how fast you respond.

**Comment by DillonHammill** [comment]
No worries, I will close for now. Feel free to reopen this issue if you need more help with this.
