### ISSUE TITLE
automated gating from template

### ISSUE THREAD

**Issue by antoine4ucsd** [DillonHammill/CytoExploreR#93]
First of all, congrats for your amazing work.
I am trying to apply a gating template to a large number of samples. My goal is to automatize as mush as possible isolation of live cells. 
As expected, when plotting all samples together, some appears 'outliers' or not well gated. is there a way to adjust the gating from a multipanel plot (i.e. not opening each fcs one by one)?
  
I am attaching one example where I could refine the gating for the #5 and #6 sample. I'd like to work from this multi-panel plot (especially when dealing with >100 samples...)
All suggestions or alternatives are vey welcome!
thank you
 
![_0_Activation SingleCells_1-10](https://user-images.githubusercontent.com/18502631/96925252-b9207b00-1468-11eb-91cc-72321bfeaab1.png)

**Comment by DillonHammill** [comment]
@antoine4ucsd, I am going to need some more information if I am going to be able to help you with this. Which cells are you trying to gate? Are there any additional parental gates that have been applied? Do you want to set the same gates across samples or gate samples separately? What you have you tried to attempt to gate this data? If you provide some code I can give you a hand.

**Comment by antoine4ucsd** [comment]
thank you for the quick reply! I was trying to gate live cells using a template (attached) and applying it to a large number of samples (~300) at once: as expected this is not perfect so I was wondering if there would be a way to adjust the gating manually 'quickly' by eye-balling all samples at once (and not going back to each sample separately...)
I hope it makes sense...


[Uploading _MygatingTemplate_Live_Activa
[Uploading _MygatingTemplate_Live_Activate.2020-10-20.csv.zip…]()
te.2020-10-20.csv…]()

**Comment by DillonHammill** [comment]
Looks like the upload didn't quite work...

**Comment by antoine4ucsd** [comment]
trying again
[_MygatingTemplate_Live_Activate.2020-10-20.csv.zip](https://github.com/DillonHammill/CytoExploreR/files/5426349/_MygatingTemplate_Live_Activate.2020-10-20.csv.zip)

**Comment by DillonHammill** [comment]
@antoine4ucsd, looks like you are using an old version of CytoExploreR - I would recommend that you update the package before proceeding:
```{r}
library(BiocManager)
install("cytolib", "flowCore", "flowWorkspace", "openCyto")

library(devtools)
devtools::install_github("DillonHammill/CytoExploreR")
```

I would also advise looking at the updated website as much of the original functionality has changed/improved:
https://dillonhammill.github.io/CytoExploreR/ 

You will need to re-gate the data from scratch using the new version of CytoExploreR.

I think that you will find that your question is answered there. Since you are using so many samples I would recommend using a subset of them when gating using the new `select` argument. For example, if you want to apply the same gate to all samples, you could use a random subset of 20 samples for gating:
```{r}
cyto_gate_draw(gs,
parent = "Single Cells",
alias = "Live Cells",
channels = c("AmCyan-A", "FSC-H"),
select = sample(1:length(gs), 20)) # use 20 random samples
```
These samples will be pooled and plotted in a single plot that you can gate, you can control the number of events to display by changing the `display` argument (e.g. `display = 50000).

**Comment by antoine4ucsd** [comment]
ok. You are right, I will start from scratch with the updated version.
thank you for your responsiveness.
